### ISSUE TITLE
Using NovaResource complains about an Argument #1 ($attributes) must be of type array, string given

### ISSUE THREAD

**Issue by glouel** [dcasia/resource-navigation-link#18]
Hey there,

I'm fairly new to Nova, so apologies in advance as I'm probably doing something wrong. I'm getting this error when trying to use a couple of NovaResources : 

```
[2021-09-08 18:55:26] local.ERROR: Illuminate\Database\Eloquent\Builder::make(): Argument #1 ($attributes) must be of type array, string given, called in /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php on line 23 {"userId":1,"exception":"[object] (TypeError(code: 0): Illuminate\\Database\\Eloquent\\Builder::make(): Argument #1 ($attributes) must be of type array, string given, called in /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php on line 23 at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:134)
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(23): Illuminate\\Database\\Eloquent\\Builder->make()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2091): Illuminate\\Database\\Eloquent\\Model->forwardCallTo()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(23): Illuminate\\Database\\Eloquent\\Model->__call()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Resources/DelegatesToResource.php(152): Laravel\\Nova\\Resource->forwardCallTo()
#4 /var/www/html/app/Nova/Besoin.php(72): Laravel\\Nova\\Resource->__call()
```

What I did is add the cards to an existing resource I had previously created. Maybe this is wrong, but here's the code : 

```
use Laravel\Nova\Resource as NovaResource;
use DigitalCreative\ResourceNavigationLink\ResourceNavigationLink;

class Besoin extends Resource
{

... 

    public function cards(Request $request)
    {
        return [
            ResourceNavigationLink::make([
                'Resource 1' => NovaResource::make(\App\Nova\Objectif::class),
                'Resource 2' => NovaResource::make(\App\Nova\Action::class),
            ]),
        ];
    }
```

Any idea of what I'm doing wrong?

**Comment by milewski** [comment]
You are using `Laravel\Nova\Resource` instead of `DigitalCreative\CollapsibleResourceManager\Resources\NovaResource`

**Comment by milewski** [comment]
You are using `Laravel\Nova\Resource` instead of `DigitalCreative\CollapsibleResourceManager\Resources\NovaResource`, I guess the documentation wasnt clear that you also need the `CollapsibleResourceManager` manage package  https://github.com/dcasia/collapsible-resource-manager

**Comment by glouel** [comment]
Thanks for your super quick response, indeed that was the issue and it works now. 

May I suggest possibly expanding a tiny bit the `readme` with an example that says that if you want to link multiple resource, the same card should be on all the resources (if that makes sense).

Thanks again for your package and support !
